apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: '2'
    machine.openshift.io/memoryMb: '174080'
    machine.openshift.io/vCPU: '24'
  name: asa-demo-ddbx4-worker-gpu
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: asa-demo-ddbx4
      machine.openshift.io/cluster-api-machineset: asa-demo-ddbx4-worker-gpu
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: asa-demo-ddbx4
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: asa-demo-ddbx4-worker-gpu
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          machineType: a2-highgpu-2g
          userDataSecret:
            name: worker-user-data
          deletionProtection: false
          networkInterfaces:
            - network: asa-demo-ddbx4-network
              subnetwork: asa-demo-ddbx4-worker-subnet
          onHostMaintenance: Terminate
          credentialsSecret:
            name: gcp-cloud-credentials
          zone: us-central1-b
          canIPForward: false
          projectID: openenv-7mhsq
          region: us-central1
          kind: GCPMachineProviderSpec
          disks:
            - autoDelete: true
              boot: true
              image: projects/rhcos-cloud/global/images/rhcos-418-94-202501221327-0-gcp-x86-64
              labels: {}
              sizeGb: 256
              type: pd-ssd
          tags:
            - asa-demo-ddbx4-worker
          serviceAccounts:
            - email: asa-demo-ddbx4-w@openenv-7mhsq.iam.gserviceaccount.com
              scopes:
                - 'https://www.googleapis.com/auth/cloud-platform'
          apiVersion: machine.openshift.io/v1beta1
          shieldedInstanceConfig: {}

