apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-image-selection: s2i-minimal-notebook:2025.2
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-size-selection: Small
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.asa-demo.7mhsq.gcp.redhatworkshops.io/projects/loan-rate-model?notebookLogout=loan-rate-model-dev
    opendatahub.io/accelerator-name: ""
    opendatahub.io/accelerator-profile-namespace: ""
    opendatahub.io/hardware-profile-name: ""
    opendatahub.io/hardware-profile-namespace: ""
    opendatahub.io/image-display-name: Jupyter | Minimal | CPU | Python 3.12
    opendatahub.io/legacy-hardware-profile-name: ""
    opendatahub.io/username: kube:admin
    opendatahub.io/workbench-image-namespace: ""
    openshift.io/description: ""
    openshift.io/display-name: loan-rate-model-dev
  finalizers:
  - notebook-oauth-client-finalizer.opendatahub.io
  generation: 2
  labels:
    app: loan-rate-model-dev
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: kube-3aadmin
  name: loan-rate-model-dev
  namespace: loan-rate-model
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/loan-rate-model/loan-rate-model-dev
                              --ServerApp.quit_button=False
                              --ServerApp.tornado_settings={"user":"kube-3aadmin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.asa-demo.7mhsq.gcp.redhatworkshops.io","hub_prefix":"/projects/loan-rate-model"}
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2025.2
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:2025.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/loan-rate-model/loan-rate-model-dev/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: loan-rate-model-dev
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/loan-rate-model/loan-rate-model-dev/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: loan-rate-model-dev-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=loan-rate-model-dev
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --client-id=loan-rate-model-dev-loan-rate-model-oauth-client
        - --client-secret-file=/etc/oauth/client/secret
        - --scope=user:info user:check-access
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"loan-rate-model-dev","namespace":"$(NAMESPACE)"}
        - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.asa-demo.7mhsq.gcp.redhatworkshops.io/projects/loan-rate-model?notebookLogout=loan-rate-model-dev
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:c174c11374a52ddb7ecfa400bbd9fe0c0f46129bd27458991bec69237229ac7d
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/client
          name: oauth-client
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: loan-rate-model-dev
      volumes:
      - name: loan-rate-model-dev-storage
        persistentVolumeClaim:
          claimName: loan-rate-model-dev-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: loan-rate-model-dev-oauth-config
      - name: oauth-client
        secret:
          defaultMode: 420
          secretName: loan-rate-model-dev-oauth-client
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: loan-rate-model-dev-tls
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
status:
  conditions:
  - lastProbeTime: "2025-11-05T19:35:10Z"
    lastTransitionTime: "2025-10-23T19:21:22Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: "2025-11-05T19:35:10Z"
    lastTransitionTime: "2025-10-23T19:20:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: "2025-11-05T19:35:10Z"
    lastTransitionTime: "2025-10-23T19:21:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: "2025-11-05T19:35:10Z"
    lastTransitionTime: "2025-10-23T19:21:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: "2025-11-05T19:35:10Z"
    lastTransitionTime: "2025-10-23T19:20:21Z"
    status: "True"
    type: PodScheduled
  containerState:
    running:
      startedAt: "2025-10-23T19:21:14Z"
  readyReplicas: 1
